import { Report } from '@/src/types';

export const MOCK_REPORTS: Report[] = [
    {
        id: 1,
        lat: 55.7558,
        long: 37.6173,
        title: 'Яма во дворе',
        desc: 'Огромная яма при въезде во двор, машины цепляют дном.',
        address: 'ул. Пушкина, д. 10',
        status: 'pending',
        category: 'road',
        date: '12.10.2023',
        author: 'Иван П.',
        likes: 5,
        comments: 2,
        image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400',
    },
    {
        id: 4,
        lat: 55.7558,
        long: 37.6173,
        title: 'Сломан забор',
        desc: 'Дети выломали секцию забора, опасно.',
        address: 'ул. Пушкина, д. 10',
        status: 'pending',
        category: 'house',
        date: '14.10.2023',
        author: 'Мария В.',
        likes: 2,
        comments: 1,
        image: null,
    },
    {
        id: 2,
        lat: 55.7308,
        long: 37.5988,
        title: 'Не горит фонарь',
        desc: 'Вдоль аллеи не работает освещение уже неделю.',
        address: 'Парк Горького',
        status: 'solved',
        category: 'light',
        date: '10.10.2023',
        author: 'Анна С.',
        likes: 12,
        comments: 0,
        image: 'https://images.unsplash.com/photo-1550523117-9c5224329249?auto=format&fit=crop&q=80&w=400',
    },
    {
        id: 3,
        lat: 55.7512,
        long: 37.6184,
        title: 'Мусор не вывозят',
        desc: 'Контейнеры переполнены, запах на весь район.',
        address: 'пр. Ленина, 42',
        status: 'progress',
        category: 'trash',
        date: '09.10.2023',
        author: 'Дмитрий К.',
        likes: 8,
        comments: 4,
        image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=400',
    },
];
