import { Report } from '@/src/types';

export const MOCK_REPORTS: Report[] = [
    {
        id: 1,
        latitude: 53.20,
        longitude: 50.15,
        title: 'Яма во дворе',
        description: 'Огромная яма при въезде во двор, машины цепляют дном.',
        address: 'ул. Пушкина, д. 10',
        status: 'pending',
        rubric_name: 'Дороги',
        created_at: '2023-10-12T10:00:00Z',
        author_username: 'Иван П.',
        preview_photo: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400',
    },
    {
        id: 4,
        latitude: 53.20,
        longitude: 50.18,
        title: 'Сломан забор',
        description: 'Дети выломали секцию забора, опасно.',
        address: 'ул. Пушкина, д. 10',
        status: 'pending',
        rubric_name: 'ЖКХ',
        created_at: '2023-10-14T10:00:00Z',
        author_username: 'Мария В.',
        preview_photo: null,
    },
    {
        id: 2,
        latitude: 53.20,
        longitude: 50.16,
        title: 'Не горит фонарь',
        description: 'Вдоль аллеи не работает освещение уже неделю.',
        address: 'Парк Горького',
        status: 'solved',
        rubric_name: 'Свет',
        created_at: '2023-10-10T10:00:00Z',
        author_username: 'Анна С.',
        preview_photo: 'https://images.unsplash.com/photo-1550523117-9c5224329249?auto=format&fit=crop&q=80&w=400',
    },
    {
        id: 3,
        latitude: 53.2025,
        longitude: 50.1510,
        title: 'Мусор не вывозят',
        description: 'Контейнеры переполнены, запах на весь район.',
        address: 'пр. Ленина, 42',
        status: 'progress',
        rubric_name: 'Мусор',
        created_at: '2023-10-09T10:00:00Z',
        author_username: 'Дмитрий К.',
        preview_photo: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=400',
    },
];
